import { ImageSourcePropType } from 'react-native';

import Heavyrain from '../assets/images/heavyrain.png';
import Moderaterain from '../assets/images/moderaterain.png';
import Snow from '../assets/images/snow.png';
import Mist from '../assets/images/mist.png';
import Sun from '../assets/images/sun.png';
import Partlycloudy from '../assets/images/partlycloudy.png';
import Cloud from '../assets/images/cloud.png';

import CloudBg from '../assets/gif/cloud.jpg';
import RainBg from '../assets/gif/rain.jpg';
import SnowBg from '../assets/gif/snow.jpg';
import SunBg from '../assets/gif/sun.jpg';

const appid = 'be7e9a9c61fecdb8c9e38ac53feedc27';

const weatherImage: { [key in string]: ImageSourcePropType } = {
   '11d': Heavyrain,
   '11n': Heavyrain,
   '09d': Heavyrain,
   '09n': Heavyrain,
   '10d': Moderaterain,
   '10n': Moderaterain,
   '13d': Snow,
   '13n': Snow,
   '50d': Mist,
   '50n': Mist,
   '01d': Sun,
   '01n': Sun,
   '02d': Partlycloudy,
   '02n': Partlycloudy,
   '03d': Cloud,
   '03n': Cloud,
   '04d': Cloud,
   '04n': Cloud
}

const weatherImageBackground: { [key in string]: ImageSourcePropType } = {
   '11d': RainBg,
   '11n': RainBg,
   '09d': RainBg,
   '09n': RainBg,
   '10d': RainBg,
   '10n': RainBg,
   '13d': SnowBg,
   '13n': SnowBg,
   '50d': CloudBg,
   '50n': CloudBg,
   '01d': SunBg,
   '01n': SunBg,
   '02d': SunBg,
   '02n': SunBg,
   '03d': CloudBg,
   '03n': CloudBg,
   '04d': CloudBg,
   '04n': CloudBg
}

const countryCodes: { [key in string]: string } = {
   "AF": "Afghanistan",
   "AX": "Åland Islands",
   "AL": "Albania",
   "DZ": "Algeria",
   "AS": "American Samoa",
   "AD": "Andorra",
   "AO": "Angola",
   "AI": "Anguilla",
   "AQ": "Antarctica",
   "AG": "Antigua and Barbuda",
   "AR": "Argentina",
   "AM": "Armenia",
   "AW": "Aruba",
   "AU": "Australia",
   "AT": "Austria",
   "AZ": "Azerbaijan",
   "BS": "Bahamas",
   "BH": "Bahrain",
   "BD": "Bangladesh",
   "BB": "Barbados",
   "BY": "Belarus",
   "BE": "Belgium",
   "BZ": "Belize",
   "BJ": "Benin",
   "BM": "Bermuda",
   "BT": "Bhutan",
   "BO": "Bolivia",
   "BQ": "Bonaire, Sint Eustatius and Saba",
   "BA": "Bosnia and Herzegovina",
   "BW": "Botswana",
   "BV": "Bouvet Island",
   "BR": "Brazil",
   "IO": "British Indian Ocean Territory",
   "BN": "Brunei",
   "BG": "Bulgaria",
   "BF": "Burkina Faso",
   "BI": "Burundi",
   "CV": "Cabo Verde",
   "KH": "Cambodia",
   "CM": "Cameroon",
   "CA": "Canada",
   "KY": "Cayman Islands",
   "CF": "Central African Republic",
   "TD": "Chad",
   "CL": "Chile",
   "CN": "China",
   "CX": "Christmas Island",
   "CC": "Cocos (Keeling) Islands",
   "CO": "Colombia",
   "KM": "Comoros",
   "CG": "Congo",
   "CD": "Congo, Democratic Republic of the",
   "CK": "Cook Islands",
   "CR": "Costa Rica",
   "CI": "Côte d'Ivoire",
   "HR": "Croatia",
   "CU": "Cuba",
   "CW": "Curaçao",
   "CY": "Cyprus",
   "CZ": "Czech Republic",
   "DK": "Denmark",
   "DJ": "Djibouti",
   "DM": "Dominica",
   "DO": "Dominican Republic",
   "EC": "Ecuador",
   "EG": "Egypt",
   "SV": "El Salvador",
   "GQ": "Equatorial Guinea",
   "ER": "Eritrea",
   "EE": "Estonia",
   "ET": "Ethiopia",
   "FK": "Falkland Islands (Malvinas)",
   "FO": "Faroe Islands",
   "FJ": "Fiji",
   "FI": "Finland",
   "FR": "France",
   "GF": "French Guiana",
   "PF": "French Polynesia",
   "TF": "French Southern Territories",
   "GA": "Gabon",
   "GM": "Gambia",
   "GE": "Georgia",
   "DE": "Germany",
   "GH": "Ghana",
   "GI": "Gibraltar",
   "GR": "Greece",
   "GL": "Greenland",
   "GD": "Grenada",
   "GP": "Guadeloupe",
   "GU": "Guam",
   "GT": "Guatemala",
   "GG": "Guernsey",
   "GN": "Guinea",
   "GW": "Guinea-Bissau",
   "GY": "Guyana",
   "HT": "Haiti",
   "HM": "Heard Island and McDonald Islands",
   "VA": "Vatican City",
   "HN": "Honduras",
   "HK": "Hong Kong",
   "HU": "Hungary",
   "IS": "Iceland",
   "IN": "India",
   "ID": "Indonesia",
   "IR": "Iran",
   "IQ": "Iraq",
   "IE": "Ireland",
   "IM": "Isle of Man",
   "IL": "Israel",
   "IT": "Italy",
   "JM": "Jamaica",
   "JP": "Japan",
   "JE": "Jersey",
   "JO": "Jordan",
   "KZ": "Kazakhstan",
   "KE": "Kenya",
   "KI": "Kiribati",
   "KP": "North Korea",
   "KR": "South Korea",
   "KW": "Kuwait",
   "KG": "Kyrgyzstan",
   "LA": "Laos",
   "LV": "Latvia",
   "LB": "Lebanon",
   "LS": "Lesotho",
   "LR": "Liberia",
   "LY": "Libya",
   "LI": "Liechtenstein",
   "LT": "Lithuania",
   "LU": "Luxembourg",
   "MO": "Macao",
   "MK": "North Macedonia",
   "MG": "Madagascar",
   "MW": "Malawi",
   "MY": "Malaysia",
   "MV": "Maldives",
   "ML": "Mali",
   "MT": "Malta",
   "MH": "Marshall Islands",
   "MQ": "Martinique",
   "MR": "Mauritania",
   "MU": "Mauritius",
   "YT": "Mayotte",
   "MX": "Mexico",
   "FM": "Micronesia",
   "MD": "Moldova",
   "MC": "Monaco",
   "MN": "Mongolia",
   "ME": "Montenegro",
   "MS": "Montserrat",
   "MA": "Morocco",
   "MZ": "Mozambique",
   "MM": "Myanmar (Burma)",
   "NA": "Namibia",
   "NR": "Nauru",
   "NP": "Nepal",
   "NL": "Netherlands",
   "NC": "New Caledonia",
   "NZ": "New Zealand",
   "NI": "Nicaragua",
   "NE": "Niger",
   "NG": "Nigeria",
   "NU": "Niue",
   "NF": "Norfolk Island",
   "MP": "Northern Mariana Islands",
   "NO": "Norway",
   "OM": "Oman",
   "PK": "Pakistan",
   "PW": "Palau",
   "PS": "Palestine, State of",
   "PA": "Panama",
   "PG": "Papua New Guinea",
   "PY": "Paraguay",
   "PE": "Peru",
   "PH": "Philippines",
   "PN": "Pitcairn",
   "PL": "Poland",
   "PT": "Portugal",
   "PR": "Puerto Rico",
   "QA": "Qatar",
   "RE": "Réunion",
   "RO": "Romania",
   "RU": "Russia",
   "RW": "Rwanda",
   "BL": "Saint Barthélemy",
   "SH": "Saint Helena, Ascension and Tristan da Cunha",
   "KN": "Saint Kitts and Nevis",
   "LC": "Saint Lucia",
   "MF": "Saint Martin (French part)",
   "PM": "Saint Pierre and Miquelon",
   "VC": "Saint Vincent and the Grenadines",
   "WS": "Samoa",
   "SM": "San Marino",
   "ST": "Sao Tome and Principe",
   "SA": "Saudi Arabia",
   "SN": "Senegal",
   "RS": "Serbia",
   "SC": "Seychelles",
   "SL": "Sierra Leone",
   "SG": "Singapore",
   "SX": "Sint Maarten (Dutch part)",
   "SK": "Slovakia",
   "SI": "Slovenia",
   "SB": "Solomon Islands",
   "SO": "Somalia",
   "ZA": "South Africa",
   "GS": "South Georgia and the South Sandwich Islands",
   "SS": "South Sudan",
   "ES": "Spain",
   "LK": "Sri Lanka",
   "SD": "Sudan",
   "SR": "Suriname",
   "SJ": "Svalbard and Jan Mayen",
   "SZ": "Eswatini",
   "SE": "Sweden",
   "CH": "Switzerland",
   "SY": "Syria",
   "TW": "Taiwan",
   "TJ": "Tajikistan",
   "TZ": "Tanzania",
   "TH": "Thailand",
   "TL": "Timor-Leste",
   "TG": "Togo",
   "TK": "Tokelau",
   "TO": "Tonga",
   "TT": "Trinidad and Tobago",
   "TN": "Tunisia",
   "TR": "Turkey",
   "TM": "Turkmenistan",
   "TC": "Turks and Caicos Islands",
   "TV": "Tuvalu",
   "UG": "Uganda",
   "UA": "Ukraine",
   "AE": "United Arab Emirates",
   "GB": "United Kingdom",
   "US": "United States",
   "UM": "United States Minor Outlying Islands",
   "UY": "Uruguay",
   "UZ": "Uzbekistan",
   "VU": "Vanuatu",
   "VE": "Venezuela",
   "VN": "Vietnam",
   "VG": "Virgin Islands, British",
   "VI": "Virgin Islands, U.S.",
   "WF": "Wallis and Futuna",
   "EH": "Western Sahara",
   "YE": "Yemen",
   "ZM": "Zambia",
   "ZW": "Zimbabwe"
}

export {
   appid,
   weatherImage,
   countryCodes,
   weatherImageBackground
}